CREATE TABLE "Visites"(
	roomID INT,
	customerID INT,
	year NUMERIC NOT NULL,
	month TEXT NOT NULL,
	day NUMERIC,
	visitDay NUMERIC,
	personCount INT,
	CONSTRAINT PK_Visites PRIMARY KEY (roomID,customerID,year),
	FOREIGN KEY (roomID) REFERENCES Rooms(roomID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (customerID) REFERENCES Customers(customerID) ON DELETE NO ACTION ON UPDATE NO ACTION
	\totalPrice
	);